### ISSUE TITLE
Could you change the license?

### ISSUE THREAD

**Issue by Pidroh** [fermmm/EasierUI#1]
GPL is very restrictive and requires me to release the source code of any game that uses it

**Comment by fermmm** [comment]
which license you suggest?

**Comment by IDGG73** [comment]
Could use the MIT License, perhaps?

As far as I understand, and as @Pidroh mentioned, GPL forces any user of the library to release derivative works under GPL too, and I think that applies to games as well but I'm not entirely sure. GPL can be confusing and I usually stay clear from it because of that.

MIT is a popular choice. It basically just requires you to include a copyright notice, which could be done in a credits scene or a `.txt` file shipped with the game.

Would be cool if you could change the license, but this is your Asset after all! :D

**Comment by fermmm** [comment]
I changed the license to [LGPL](https://es.wikipedia.org/wiki/GNU_Lesser_General_Public_License) which I understand allows to use the library in a project that is proprietary or commercial without issues.

**Comment by fermmm** [comment]
I'm closing the issue, if you have any question or problem with the license open a new one.
